### ISSUE TITLE
Building by gradle on Android studio

### ISSUE THREAD

**Issue by gaplo917** [ludei/webview-plus#40]
I import the repository as a module in Android studio and try to build it with Cordova by Gradle but not ANT in cli. 

The follow error was shown

> Execution failed for task ':dexDebug'.
>  com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     /Users/Gaplo917/Android/sdk/build-tools/21.1.1/dx --dex --no-optimize --output /Users/Gaplo917/PhoneGapProejct/testCocoonjs/platforms/android/build/intermediates/dex/debug --input-list=/Users/Gaplo917/PhoneGapProejct/testCocoonjs/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
>   Error Code:
>     2
>   Output:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/ludei/chromium/BuildConfig;
```

I think the root of the problem is the .jar files contains the BuildConfig file which will collide with the one generated by gradle. The proof is when I change the package name in AndroidMainifest.xml of webview+, ie. com.luidei.android.chromium instead of com.luidei.chromium. The project can be built with webview+ in  "debug" type ONLY but not in "release".

Purpose : I successfully did a project of  Some Native(Augmented Reality) + HTML5 Game with CordovaWebView, I want to accelerate the CordovaWebView by replacing the webview by webview+ to have the V8 complier on the low end model (Non 4.4 device and fix the 4.4.2 chromium bug https://code.google.com/p/chromium/issues/detail?id=315111).

**Comment by a-vladev-appchef** [comment]
I've opened the jar file (it's a zip file) and removed the BuildConfig or R file (i can't remember which) also put ```multiDexEnabled true``` in build.gradle in my main project.
