### ISSUE TITLE
source code and license

### ISSUE THREAD

**Issue by alexkb** [ludei/webview-plus#48]
I can't seem to find any sourcecode for this plugin, as it appears to be committed in a compiled state. Am I looking in the wrong place or was this intended?

Could you also advise which software license this plugin is released under as there's no LICENSE.txt in the repo. In the current state (no license specified) the [github terms state](https://help.github.com/articles/open-source-licensing/) that

> ".. nobody else may reproduce, distribute, or create derivative works from your work"

This seems kind of crazy if it's part of a mobile app users distribute to their customers on app stores. Thanks.

**Comment by alexkb** [comment]
The changelog indicates that Chromium is used, which is [licensed under the BSD license](http://en.wikipedia.org/wiki/Chromium_%28web_browser%29#Licensing). It would be good to know what's been added or changed from Chromium so we can add to or improve on.

**Comment by LibelulaV** [comment]
I have just included the source code: https://github.com/ludei/webview-plus/tree/master/source

The 1.0.37 is the latest version used. The 1.0.39 is the newest, but not fully tested. 
Sorry for the delay. 

Regards, 

Marta.

**Comment by alexkb** [comment]
Thanks Marta, much appreciated.
