### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by ssavajols** [ludei/webview-plus#52]
Hi,

When I use this command :
cocoonjs plugin add com.ludei.webview.plus -d

I got this message :
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.ludei.webview.plus

What ma I doing wrong ?

Thanks.

**Comment by BlueSialia** [comment]
This project is discontinued and we do not offer support. Use our new tool at [Cocoon.io](https://cocoon.io/) to create applications with the new Webview+.
